### ISSUE TITLE
Doesn't work with ember-templates-compiler 2.7.2, but works with 2.3.0

### ISSUE THREAD

**Issue by sevarubbo** [dgeb/grunt-ember-templates#91]
Got an error `TypeError: (module.exports || exports).precompile is not a function`

**Comment by zoltan-nz** [comment]
Thanks @sevarubbo I look into it.

**Comment by zoltan-nz** [comment]
Fix: https://github.com/dgeb/grunt-ember-templates/issues/91

**Comment by zoltan-nz** [comment]
Fix: https://github.com/dgeb/grunt-ember-templates/pull/92
